service: ts-api

provider:
  name: aws
  profile: serverless-admin
  region: ${self:custom.config.region}
  runtime: python3.6
  stage: ${self:custom.config.stage}
  versionFunctions: false

  iamRoleStatements:
    ${self:custom.config.iam.role-statement}

  memorySize: 128
  timeout: 30
  apiName: twitch-stitch-${self:custom.config.stage}

package:
  exclude:
    - '*/**'
  include:
    - modules/**/run.py

plugins:
  - serverless-python-requirements

custom:
  userPoolId: us-west-2_DHhjlIxKV
  config: ${file(../ts_shared/ts_config/ts_config/ts_config.yml)}
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true
    pipCmdExtraArgs:
      - --process-dependency-links
    slim: true

functions:
  - ${file(./config/apis.yml)}
