service: ts-api

provider:
  name: aws
  profile: serverless-admin
  region: ${self:custom.config.aws.region}
  runtime: python3.6
  stage: dev
  versionFunctions: false

  iamRoleStatements:
    ${self:custom.config.aws.iam.role-statement}

  memorySize: 128
  timeout: 30
  apiName: TwitchStitch
  apiKeys:
    - TwitchStitchApiKey

package:
  individually: true
  exclude:
    - '*/**'

plugins:
  - serverless-python-requirements

custom:
  config: ${file(../ts_shared/ts_config/ts_config/ts_config.yml)}
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true

functions:
  - ${file(./config/apis.yml)}
