service: twitch-stitch-api

provider:
  name: aws
  memorySize: 512
  profile: serverless-admin
  region: us-west-1
  runtime: python3.6
  stackName: twitch-stitch-sls-api
  stage: dev
  timeout: 30
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource: arn:aws:dynamodb:us-west-1:*:*
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource: arn:aws:sqs:us-west-1:*:*

  apiKeys:
    - ts_api_key

package:
  individually: true
  exclude:
    - '*/**'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true

functions:
  - ${file(./config/apis.yml)}

