api--moments--create:
  handler: run.run
  module: modules/moments__create
  events:
      - http:
          path: stream/{stream_id}/moments
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:custom.config.region}:${self:custom.config.account-id}:userpool/${self:custom.userPoolId}

api--montage--create:
  handler: run.run
  module: modules/montage__create
  events:
      - http:
          path: montage
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:custom.config.region}:${self:custom.config.account-id}:userpool/${self:custom.userPoolId}

api--montages--get:
  handler: run.run
  module: modules/montages__get
  events:
      - http:
          path: montages
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:custom.config.region}:${self:custom.config.account-id}:userpool/${self:custom.userPoolId}

api--montages--get-recent:
  handler: run.run
  module: modules/montages__get_recent
  events:
      - http:
          path: montages/recent
          method: get
          cors: true

api--stream--get:
  handler: run.run
  module: modules/stream__get
  events:
      - http:
          path: stream/{stream_id}
          method: get
          cors: true

api--streams--get-recent:
  handler: run.run
  module: modules/streams__get_recent
  events:
      - http:
          path: streams/recent
          method: get
          cors: true
