api--clip--create:
  handler: run.run
  module: modules/clip__create
  events:
      - http:
          path: clip
          method: post
          cors: true
          private: true
  package:
    include:
      - modules/clip__create/run.py

api--clip--get-all:
  handler: run.run
  module: modules/clip__get_all
  events:
      - http:
          path: clip
          method: get
          cors: true
          private: true
  package:
    include:
      - modules/clip__get_all/run.py

api--montage--create:
  handler: run.run
  module: modules/montage__create
  events:
      - http:
          path: montage
          method: post
          cors: true
          private: true
  package:
    include:
      - modules/montage__create/run.py

api--montage--get-all:
  handler: run.run
  module: modules/montage__get_all
  events:
      - http:
          path: montage
          method: get
          cors: true
          private: true
  package:
    include:
      - modules/montage__get_all/run.py
