api--clip--create:
  handler: run.run
  module: modules/clip__create
  events:
      - http:
          path: clip
          method: post
          cors: true
          private: true
  package:
    include:
      - modules/clip__create/run.py

api--clips--get:
  handler: run.run
  module: modules/clips__get
  events:
      - http:
          path: clips
          method: get
          cors: true
          private: true
  package:
    include:
      - modules/clips__get/run.py

api--moments--create:
  handler: run.run
  module: modules/moments__create
  events:
      - http:
          path: stream/{stream_id}/moments
          method: post
          cors: true
          private: true
  package:
    include:
      - modules/moments__create/run.py

api--montage--create:
  handler: run.run
  module: modules/montage__create
  events:
      - http:
          path: montage
          method: post
          cors: true
          private: true
  package:
    include:
      - modules/montage__create/run.py

api--montages--get:
  handler: run.run
  module: modules/montages__get
  events:
      - http:
          path: montages
          method: get
          cors: true
          private: true
  package:
    include:
      - modules/montages__get/run.py

api--stream--get:
  handler: run.run
  module: modules/stream__get
  events:
      - http:
          path: stream/{stream_id}
          method: get
          cors: true
          private: true
  package:
    include:
      - modules/stream__get/run.py
