api--moments--create:
  handler: run.run
  module: modules/moments__create
  events:
      - http:
          path: stream/{stream_id}/moments
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:custom.config.region}:${self:custom.config.account-id}:userpool/${self:custom.userPoolId}
  package:
    include:
      - modules/moments__create/run.py

api--montage--create:
  handler: run.run
  module: modules/montage__create
  events:
      - http:
          path: montage
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:custom.config.region}:${self:custom.config.account-id}:userpool/${self:custom.userPoolId}
  package:
    include:
      - modules/montage__create/run.py

api--montages--get:
  handler: run.run
  module: modules/montages__get
  events:
      - http:
          path: montages
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:custom.config.region}:${self:custom.config.account-id}:userpool/${self:custom.userPoolId}
  package:
    include:
      - modules/montages__get/run.py

api--stream--get:
  handler: run.run
  module: modules/stream__get
  events:
      - http:
          path: stream/{stream_id}
          method: get
          cors: true
  package:
    include:
      - modules/stream__get/run.py

api--streams--get:
  handler: run.run
  module: modules/streams__get
  events:
      - http:
          path: streams
          method: get
          cors: true
  package:
    include:
      - modules/streams__get/run.py
