api-clip-create:
  handler: run.run
  module: modules/clip_create
  events:
      - http:
          path: clip
          method: post
          cors: true
          private: true
  package:
    include:
      - modules/clip_create/run.py

api-clip-get-all:
  handler: run.run
  module: modules/clip_get_all
  events:
      - http:
          path: clip
          method: get
          cors: true
          private: true
  package:
    include:
      - modules/clip_get_all/run.py

api-montage-create:
  handler: run.run
  module: modules/montage_create
  events:
      - http:
          path: montage
          method: post
          cors: true
          private: true
  package:
    include:
      - modules/montage_create/run.py

api-montage-get-all:
  handler: run.run
  module: modules/montage_get_all
  events:
      - http:
          path: montage
          method: get
          cors: true
          private: true
  package:
    include:
      - modules/montage_get_all/run.py
